/**
 * This file is the entry point for the React app, it sets up the root
 * element and renders the App component to the DOM.
 *
 * It is included in `src/index.html`.
 */

import { queryClient } from "@/lib/query-client";
import { TRPCProvider, trpc, trpcClient } from "@/lib/trpc-client";
import { QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { ThemeProvider } from "./components/theme-provider";
import { Toaster } from "./components/ui/sonner";

/*
This is generated by tailwind cli as bun 
tailwind plugin is not stable enough.
https://github.com/oven-sh/bun/issues/12878
*/
import "./styles/output.css";

/*
Generated by tanstack router cli 
as bun bundler does not support it yet.
https://tanstack.com/router/latest/docs/framework/react/routing/installation-with-router-cli
*/
import { routeTree } from "./routeTree.gen";

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const router = createRouter({
  routeTree,
  context: {
    queryClient,
    trpc,
  },
  defaultPreload: "intent",
  Wrap: ({ children }) => (
    <QueryClientProvider client={queryClient}>
      <TRPCProvider
        trpcClient={trpcClient}
        queryClient={queryClient}>
        <ThemeProvider>
          {children}
          <Toaster />
        </ThemeProvider>
      </TRPCProvider>
    </QueryClientProvider>
  ),
  notFoundMode: "root",
  defaultNotFoundComponent: () => <div>Not Found</div>,
  defaultErrorComponent: () => <div>Error</div>,
});

const elem = document.getElementById("root")!;
const app = (
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>
);
if (import.meta.hot) {
  // With hot module reloading, `import.meta.hot.data` is persisted.
  const root = (import.meta.hot.data.root ??= createRoot(elem));
  root.render(app);
} else {
  // The hot module reloading API is not available in production.
  createRoot(elem).render(app);
}
